version: 0.2
phases:
  pre_build:
    commands:
      - aws --version
      - echo Logging in to Amazon ECR....
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_URI
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPO_NAME:latest .
      - docker tag $REPO_NAME:latest $ECR_URI/$REPO_NAME:latest
      - docker tag $REPO_NAME:latest $ECR_URI/$REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo pushing to AWS ECR 
      - docker push $ECR_URI/$REPO_NAME:latest
      - docker push $ECR_URI/$REPO_NAME:$IMAGE_TAG
artifacts:
  files:
    - appspec.yml
    - scripts/start-process.sh
